var dataObj={
    "left_menu_item":[
        {
            "item_name":"常用推荐",
            "item_data":[
                {
                    "tool_name":"站酷",
                    "tool_link":"http://www.zcool.com.cn/",
                    "tool_icon_code":"#icon-zhanku123",
                    "tool_icon_description":"最具人气的设计师互动平台,300万设计师聚集地。"
                },
                {
                    "tool_name":"求字体",
                    "tool_link":"http://www.qiuziti.com/",
                    "tool_icon_code":"#icon-qiuziti",
                    "tool_icon_description":"上传图片找字体、字体实时预览及字体下载服务"
                },
                {
                    "tool_name":"iconfont",
                    "tool_link":"http://www.iconfont.cn/",
                    "tool_icon_code":"#icon-iconfont",
                    "tool_icon_description":"阿里巴巴矢量图标库"
                },
                {
                    "tool_name":"学UI网",
                    "tool_link":"http://www.xueui.cn/",
                    "tool_icon_code":"#icon-xueUIwang",
                    "tool_icon_description":"UI学习教程网站"
                },
                {
                    "tool_name":"全景网",
                    "tool_link":"http://www.quanjing.com/",
                    "tool_icon_code":"#icon-quanjingwang",
                    "tool_icon_description":"中国最大的图片库和正版图片素材网站"
                },
                {
                    "tool_name":"昵图网",
                    "tool_link":"http://www.nipic.com/index.html",
                    "tool_icon_code":"#icon-nituwang",
                    "tool_icon_description":"原创素材共享平台.图片素材图库提供海量原创素材,图片下载"
                }
            ]
        },
        {
            "item_name":"设计教程",
            "item_data":[
                {
                    "tool_name":"学UI网",
                    "tool_link":"http://www.xueui.cn/",
                    "tool_icon_code":"#icon-xueUIwang",
                    "tool_icon_description":"UI学习教程网站"
                },
                {
                    "tool_name":"站酷",
                    "tool_link":"http://www.zcool.com.cn/",
                    "tool_icon_code":"#icon-zhanku123",
                    "tool_icon_description":"最具人气的设计师互动平台,300万设计师聚集地。"
                },
                {
                    "tool_name":"设计派",
                    "tool_link":"http://www.shejipai.cn/",
                    "tool_icon_code":"#icon-shejipai",
                    "tool_icon_description":"网页设计为主的设计师交流平台"
                },
                {
                    "tool_name":"UEhtml",
                    "tool_link":"http://www.uehtml.com/",
                    "tool_icon_code":"#icon-UEhtml",
                    "tool_icon_description":"专为热爱网页设计、界面设计的你而倾力打造"
                },
                {
                    "tool_name":"优设网",
                    "tool_link":"http://www.uisdc.com/",
                    "tool_icon_code":"#icon-youshewang",
                    "tool_icon_description":"优秀网页设计联盟"
                },
                {
                    "tool_name":"优阁网",
                    "tool_link":"http://www.uigreat.com/",
                    "tool_icon_code":"#icon-yougewang",
                    "tool_icon_description":"UI设计师学习交流分享的平台,免费的UI设计公开课"
                },
                {
                    "tool_name":"思源设计",
                    "tool_link":"http://www.missyuan.net/",
                    "tool_icon_code":"#icon-siyuansheji",
                    "tool_icon_description":"提供最新最全的PS设计方面教程"
                }
            ]
        },
        {
            "item_name":"icon图标",
            "item_data":[
                {
                    "tool_name":"iconfont",
                    "tool_link":"http://www.iconfont.cn/",
                    "tool_icon_code":"#icon-iconfont",
                    "tool_icon_description":"阿里巴巴矢量图标库"
                },
                {
                    "tool_name":"icons8",
                    "tool_link":"https://zh.icons8.com/",
                    "tool_icon_code":"#icon-tubiaoku",
                    "tool_icon_description":"图标库网站"
                },
                {
                    "tool_name":"测试文件夹",
                    "tool_link":"https://zh.icons8.com/",
                    "tool_icon_code":"#icon-wenjianjia",
                    "tool_icon_description":"图标库网站",
                    "next_level":[
                        {
                            "tool_name":"优设网",
                            "tool_link":"http://www.xueui.cn/",
                            "tool_icon_code":"#icon-youshewang",
                            "tool_icon_description":"UI学习教程网站",
                            "group_title":"测试文件夹"
                        },
                        {
                            "tool_name":"求字体",
                            "tool_link":"http://www.xueui.cn/",
                            "tool_icon_code":"#icon-qiuziti",
                            "tool_icon_description":"UI学习教程网站"
                        },
                        {
                            "tool_name":"学UI网",
                            "tool_link":"http://www.xueui.cn/",
                            "tool_icon_code":"#icon-xueUIwang",
                            "tool_icon_description":"UI学习教程网站"
                        }
                    ]
                }
            ]
        },
        {
            "item_name":"学配色",
            "item_data":[
                {
                    "tool_name":"MD配色",
                    "tool_link":"https://www.materialpalette.com/",
                    "tool_icon_code":"#icon-MDpeise",
                    "tool_icon_description":"方便挑选出符合心意的质感设计配色"
                },
                {
                    "tool_name":"colorfavs",
                    "tool_link":"http://www.colorfavs.com/colors/af3646/",
                    "tool_icon_code":"#icon-colorfavs",
                    "tool_icon_description":"扁平化配色取色器"
                },
                {
                    "tool_name":"配色器",
                    "tool_link":"http://www.peise.net/tools/web/",
                    "tool_icon_code":"#icon-peiseqi",
                    "tool_icon_description":"上传图片找字体、字体实时预览及字体下载服务"
                }
            ]
        },
        {
            "item_name":"字体设计",
            "item_data":[
                {
                    "tool_name":"求字体",
                    "tool_link":"http://www.qiuziti.com/",
                    "tool_icon_code":"#icon-qiuziti",
                    "tool_icon_description":"上传图片找字体、字体实时预览及字体下载服务"
                },
                {
                    "tool_name":"字体传奇",
                    "tool_link":"http://www.ziticq.com/",
                    "tool_icon_code":"#icon-zitichuanqi",
                    "tool_icon_description":"是以字体/标志/品牌/创意/设计师学习交流/和设计直播间互动为主的一个平台"
                },
                {
                    "tool_name":"毛笔字在线生成器",
                    "tool_link":"http://www.zhenhaotv.com/",
                    "tool_icon_code":"#icon-maobizishengcheng",
                    "tool_icon_description":"我们迫切希望毛笔字在线生成器能够帮助大家认识毛笔字"
                },
                {
                    "tool_name":"字体之家",
                    "tool_link":"http://www.homefont.cn/",
                    "tool_icon_code":"#icon-zitizhijia",
                    "tool_icon_description":"字体之家提供最全的免费字体下载"
                }
            ]
        },
        {
            "item_name":"高清图库",
            "item_data":[
                {
                    "tool_name":"全景网",
                    "tool_link":"http://www.quanjing.com/",
                    "tool_icon_code":"#icon-quanjingwang",
                    "tool_icon_description":"中国最大的图片库和正版图片素材网站"
                },
                {
                    "tool_name":"500px",
                    "tool_link":"https://500px.com/popular",
                    "tool_icon_code":"#icon-500px",
                    "tool_icon_description":"一个致力于摄影分享、发现、售卖的专业平台,来自世界各地的摄影师是我们忠实的用户"
                },
                {
                    "tool_name":"千库网",
                    "tool_link":"http://588ku.com/",
                    "tool_icon_code":"#icon-qiankuwang",
                    "tool_icon_description":"国内设计师喜欢的图片素材库"
                },
                {
                    "tool_name":"优界网",
                    "tool_link":"http://97ui.com/",
                    "tool_icon_code":"#icon-youjiewang",
                    "tool_icon_description":"专注于UI素材下载的网站,提供丰富的高质精品免费UI素材"
                },
                {
                    "tool_name":"pixabay",
                    "tool_link":"https://pixabay.com/",
                    "tool_icon_code":"#icon-Pixabay",
                    "tool_icon_description":"完全高清大图，一键注册，一秒下载，让创意不停车"
                },
                {
                    "tool_name":"军火库",
                    "tool_link":"http://www.j-h-k.com/",
                    "tool_icon_code":"#icon-junhuoku",
                    "tool_icon_description":"专为设计师度身定制的集合式搜图引擎,同时收录全球最全的设计素材供设计师使用"
                }
            ]
        },
        {
            "item_name":"网页设计",
            "item_data":[
                {
                    "tool_name":"设计路上",
                    "tool_link":"http://www.design63.com.cn/",
                    "tool_icon_code":"#icon-shejilushang",
                    "tool_icon_description":"设计源于灵感，灵感源于借鉴——这是每个网页设计师都应该牢记的“成功法则”"
                },
                {
                    "tool_name":"68design",
                    "tool_link":"http://www.68design.net/",
                    "tool_icon_code":"#icon-68design1",
                    "tool_icon_description":"网页设计师联盟,国内专业网页设计人才基地,为广大设计师提供学习交流空间"
                },
                {
                    "tool_name":"reeoo",
                    "tool_link":"http://reeoo.com/",
                    "tool_icon_code":"#icon-test",
                    "tool_icon_description":"国内人气最高的酷站画廊，设计师灵感必备"
                },
                {
                    "tool_name":"UEhtml",
                    "tool_link":"http://www.uehtml.com/",
                    "tool_icon_code":"#icon-UEhtml",
                    "tool_icon_description":"专为热爱网页设计、界面设计的你而倾力打造"
                }
            ]
        },
        {
            "item_name":"平面设计",
            "item_data":[
                {
                    "tool_name":"藏标网",
                    "tool_link":"http://logonc.com/",
                    "tool_icon_code":"#icon-cangbiaowang",
                    "tool_icon_description":"提供在线logo设计欣赏、标志图片素材、公司商标设计、国外标志设计欣赏等"
                },
                {
                    "tool_name":"设计之家",
                    "tool_link":"http://www.sj33.cn/",
                    "tool_icon_code":"#icon-shejizhijia",
                    "tool_icon_description":"很全面的设计网站，以平面设计为主"
                },
                {
                    "tool_name":"视觉.me",
                    "tool_link":"http://shijue.me/",
                    "tool_icon_code":"#icon-shijueme",
                    "tool_icon_description":"最丰富的题材以及最专业的原创设计作品"
                },
                {
                    "tool_name":"LogoStock",
                    "tool_link":"http://logostock.jp/catalog/",
                    "tool_icon_code":"#icon-logo-stock",
                    "tool_icon_description":"日本Logo欣赏网站"
                }
            ]
        },
        {
            "item_name":"UI设计",
            "item_data":[
                {
                    "tool_name":"Dribbble",
                    "tool_link":"https://dribbble.com/",
                    "tool_icon_code":"#icon-dribbble",
                    "tool_icon_description":"国际一流的设计师聚集地"
                },
                {
                    "tool_name":"Behance",
                    "tool_link":"https://www.behance.net/",
                    "tool_icon_code":"#icon-Behance",
                    "tool_icon_description":"提供设计师展现和发现最美的设计"
                },
                {
                    "tool_name":"UI设计网",
                    "tool_link":"http://www.uisheji.com/",
                    "tool_icon_code":"#icon-UIshejiwang",
                    "tool_icon_description":"分类较为全面的UI设计网站，国内较早的专门针对UI设计的网站之一"
                },
                {
                    "tool_name":"图翼网",
                    "tool_link":"http://www.tuyiyi.com/",
                    "tool_icon_code":"#icon-tuyiwang",
                    "tool_icon_description":"一家专为UI设计,H5设计,GUI设计,图标UI设计等从事设计行业的UI设计师打造的UI设计交流"
                },
                {
                    "tool_name":"UI中国",
                    "tool_link":"http://www.ui.cn/",
                    "tool_icon_code":"#icon-UIzhongguo1",
                    "tool_icon_description":"专业界面交互设计平台"
                }
            ]
        }
    ],
    "right_menu_item":[
        {
            "item_name":"资源下载",
            "item_data":[
                {
                    "tool_name":"千库网",
                    "tool_link":"http://588ku.com/",
                    "tool_icon_code":"#icon-qiankuwang",
                    "tool_icon_description":"国内设计师喜欢的图片素材库,588ku.com为设计师提供各类好看免费的png图片和素材"
                },
                {
                    "tool_name":"大图网",
                    "tool_link":"http://www.daimg.com/",
                    "tool_icon_code":"#icon-datuwang",
                    "tool_icon_description":"提供最优质的影楼素材和设计素材,内容包括PSD素材,淘宝素材,婚纱模板"
                },
                {
                    "tool_name":"UIcloud",
                    "tool_link":"http://ui-cloud.com/",
                    "tool_icon_code":"#icon-uicloud",
                    "tool_icon_description":"收集优秀的用户界面设计,户界面元素搜索引擎"
                },
                {
                    "tool_name":"365psd",
                    "tool_link":"http://cn.365psd.com/",
                    "tool_icon_code":"#icon-365psd",
                    "tool_icon_description":"每天一个精品PSD分享"
                },
                {
                    "tool_name":"freebies gallery",
                    "tool_link":"http://www.freebiesgallery.com/",
                    "tool_icon_code":"#icon-test",
                    "tool_icon_description":"web设计资源及分层psd免费下载"
                },
                {
                    "tool_name":"APP模板",
                    "tool_link":"http://www.xueui.cn/category/download/app-template/",
                    "tool_icon_code":"#icon-APPmoban",
                    "tool_icon_description":"学UI网提供大量PSD素材"
                }
            ]
        },
        {
            "item_name":"尺寸规范",
            "item_data":[
                {
                    "tool_name":"UI尺寸",
                    "tool_link":"http://www.uigreat.com/page/guifan",
                    "tool_icon_code":"#icon-UIchicun",
                    "tool_icon_description":"IOS及安卓尺寸集合"
                },
                {
                    "tool_name":"APP规范",
                    "tool_link":"http://www.xueui.cn/tutorials/app-tutorials/app-code-examples-with-ui-design-method.html",
                    "tool_icon_code":"#icon-appguifan",
                    "tool_icon_description":"实例讲解APP设计规范"
                },
                {
                    "tool_name":"切图规范",
                    "tool_link":"http://www.25xt.com/appdesign/7339.html",
                    "tool_icon_code":"#icon-qietu",
                    "tool_icon_description":"APP切图命名及流程规范"
                },
                {
                    "tool_name":"字体包",
                    "tool_link":"http://www.qiuziti.com/",
                    "tool_icon_code":"#icon-zitibao",
                    "tool_icon_description":"UI设计师必备的字体"
                },
                {
                    "tool_name":"网页规范",
                    "tool_link":"http://www.xueui.cn/tutorials/web-course/web-ui-visual-design-specifications.html",
                    "tool_icon_code":"#icon-wangyeguifan",
                    "tool_icon_description":"网站视觉设计规范"
                }
            ]
        },
        {
            "item_name":"找找灵感",
            "item_data":[
                {
                    "tool_name":"花瓣网",
                    "tool_link":"http://huaban.com/",
                    "tool_icon_code":"#icon-huabanwang",
                    "tool_icon_description":"设计师寻找灵感的天堂"
                },
                {
                    "tool_name":"wallhaven",
                    "tool_link":"https://alpha.wallhaven.cc/",
                    "tool_icon_code":"#icon-wall-haven",
                    "tool_icon_description":"高清大图免费网站，图片质量超高"
                },
                {
                    "tool_name":"pexels",
                    "tool_link":"https://www.pexels.com/",
                    "tool_icon_code":"#icon-Pexels",
                    "tool_icon_description":"一个高清图片下载服务站点,为用户提供海量共享图片素材的网站"
                },
                {
                    "tool_name":"APP show",
                    "tool_link":"http://app.xueui.cn/",
                    "tool_icon_code":"#icon-test",
                    "tool_icon_description":"app优秀页面展示汇总"
                },
                {
                    "tool_name":"摄图网",
                    "tool_link":"http://699pic.com/",
                    "tool_icon_code":"#icon-shetuwang",
                    "tool_icon_description":"5万张无版权免费的高清大图"
                }
            ]
        }
    ]
};